[package]
name = "citadel-install"
version = "0.1.0"
authors = ["Bruce Leidl <bruce@subgraph.com>"]
homepage = "http://github.com/subgraph/citadel"

[dependencies]
libcitadel = { path = "../libcitadel" }
failure = "0.1.3"
libc = "0.2"
rpassword = "2.1.0"
